{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bank-service.fullname" . }}
  labels:
    {{- include "bank-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bank-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
